#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# $HOME/.config/polybar/launch.sh
$HOME/.config/scripts/eww -c $HOME/.config/eww/bar --restart open bar &

bspc monitor -d 1 2 3 4 5

bspc config border_width        0 
bspc config window_gap          12
bspc config left_padding        50

#bspc config normal_border_color \#B48EAD
#bspc config active_border_color \#EBCB8B
#bspc config focused_border_color \#5E81AC 

#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a zoom desktop='^5' follow=on
bspc rule -a code-oss desktop='^3'
bspc rule -a Joplin desktop='^4'
bspc rule -a DesktopEditors desktop='^1'
bspc rule -a kitty state=pseudo_tiled
bspc rule -a Unity state=floating
bspc rule -a android-studio state=pseudo_tiled
